resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
- name: gcs-export-pipelines
  type: git
  source:
    uri: https://github.com/sapient007/gcp-mpl-export.git

- name: cf-mgmt-image
  type: docker-image
  source:
    repository: pivotalservices/cf-mgmt

- name: gcloud-sdk-image
  type: docker-image
  source:
    repository: google/cloud-sdk

- name: skus
  type: gcs-resource
  source:
    bucket: ((GCS_BUCKET))
    json_key: ((GCP_KEY))
    versioned_file: nd_skus.json

jobs:
- name: download-gcp-price-json
  plan:
  - aggregate:
    - get: cf-mgmt-image
    - get: gcs-export-pipelines
  - task: download-gcp-price-json
    image: cf-mgmt-image
    config:
      platform: linux
      outputs:
      - name: nd_json
      params:
        GCP_JSON_URL: ((SKUS_URL))
      run:
        path: bash
        args:
        - "-c"
        - |
          set -eu
          echo "getting price list from $GCP_JSON_URL"

          cd nd_json
          #fetch json from url 
          curl $GCP_JSON_URL -o skus.json
          #convert to new line deliminated json
          cat skus.json | jq -c ".[]" > nd_skus.json
  - put: skus
    params:
      file: "nd_json/nd_skus.json"

- name: truncate-skus-table
  plan:
  - aggregate: 
    - get: gcloud-sdk-image
    - get: gcs-export-pipelines
    - get: skus
      passed: [download-gcp-price-json]
      trigger: true
  - task: delete-exisiting-rows
    image: gcloud-sdk-image
    config:
      platform: linux
      inputs:
      - name: gcs-export-pipelines
      params:
        GCP_KEY: ((GCP_KEY))
        GCP_PROJECT: ((GCP_PROJECT))
      run:
        path: bash
        args:
        - "-c"
        - |
          set -eu
          #login to gclouod
          echo $GCP_KEY > service.key
          gcloud auth activate-service-account --project=$GCP_PROJECT --key-file=service.key

          #bigquery query
          
          #drop all rows
          cat gcs-export-pipelines/tasks/delete.rows.sql | bq query --use_legacy_sql=False --project=$GCP_PROJECT

           #count current rows
          cat gcs-export-pipelines/tasks/count.sql | bq query --use_legacy_sql=False --project=$GCP_PROJECT
          
- name: import-skus
  plan:
  - aggregate: 
    - get: gcloud-sdk-image
    - get: gcs-export-pipelines
    - get: skus
      passed: [truncate-skus-table]
      trigger: true
  - task: import-skus
    image: gcloud-sdk-image
    config:
      platform: linux
      inputs:
      - name: gcs-export-pipelines
      - name: skus
      params:
        GCP_KEY: ((GCP_KEY))
        GCP_PROJECT: ((GCP_PROJECT))
      run:
        path: bash
        args:
        - "-c"
        - |
          set -eu
          #login to gclouod
          echo $GCP_KEY > service.key
          gcloud auth activate-service-account --project=$GCP_PROJECT --key-file=service.key

          #bigquery query
